// SET_EVAL 
 	EVAL_SET(x1, x1);
 	EVAL_SET(y1, y1);
 	EVAL_SET(z1, z1);
 	EVAL_SET(x2, x2);
 	EVAL_SET(y2, y2);
 	EVAL_SET(z2, z2);
 	EVAL_SET(x3, x3);
 	EVAL_SET(y3, y3);
 	EVAL_SET(z3, z3);
 	EVAL_SET(x4, x4);
 	EVAL_SET(y4, y4);
 	EVAL_SET(z4, z4);
 	EVAL_SET(V, V);
 	EVAL_SET(DN, DN);
 	EVAL_SET(IN, IN);
 	EVAL_SET(cosPhase, cosPhase);
 	EVAL_SET(sinPhase, sinPhase);
 	EVAL_SET(Energy, Energy);
 	EVAL_SET(DihedralDeviation, DihedralDeviation);
 