// DEFINE_EVAL
	struct {
	double	2.8;
	double	0.;
	double	0.;
	double	-2.9;
	double	0.;
	double	0.;
	double	        12
3.156 10;
	double	          6
1.73651 10;
	double	0.;
	double	DeltaX;
	double	DeltaY;
	double	DeltaZ;
	double	Energy;
	double	Evdw;
	double	Eeel;
	double	Symbol[f2.8];
	double	Symbol[f0.];
	double	Symbol[f0.];
	double	Symbol[f-2.9];
	double	Symbol[f0.];
	double	Symbol[f0.];
	double	Symbol[dh2.82.8];
	double	Symbol[dh0.0.];
	double	Symbol[dh0.0.];
	double	Symbol[dh-2.9-2.9];
	double	Symbol[dh0.0.];
	double	Symbol[dh0.0.];
	double	Symbol[oh2.80.];
	double	Symbol[oh2.80.];
	double	Symbol[oh2.8-2.9];
	double	Symbol[oh2.80.];
	double	Symbol[oh2.80.];
	double	Symbol[oh0.0.];
	double	Symbol[oh0.-2.9];
	double	Symbol[oh0.0.];
	double	Symbol[oh0.0.];
	double	Symbol[oh0.-2.9];
	double	Symbol[oh0.0.];
	double	Symbol[oh0.0.];
	double	Symbol[oh-2.90.];
	double	Symbol[oh-2.90.];
	double	Symbol[oh0.0.];
	double	NonbondDistance;
	} eval;
