#if USE_EXPLICIT_DECLARES
// declare variables
DECLARE_FLOAT(DeltaX);
DECLARE_FLOAT(DeltaY);
DECLARE_FLOAT(DeltaZ);
DECLARE_FLOAT(DistanceSquared);
DECLARE_FLOAT(Eeel);
DECLARE_FLOAT(Energy);
DECLARE_FLOAT(Evdw);
DECLARE_FLOAT(NonbondDistance);
DECLARE_FLOAT(tx15);
DECLARE_FLOAT(tx16);
DECLARE_FLOAT(tx17);
DECLARE_FLOAT(tx18);
DECLARE_FLOAT(tx19);
DECLARE_FLOAT(tx20);
DECLARE_FLOAT(tx21);
DECLARE_FLOAT(tx22);
DECLARE_FLOAT(tx23);
DECLARE_FLOAT(tx24);
DECLARE_FLOAT(tx25);
DECLARE_FLOAT(tx26);
DECLARE_FLOAT(tx27);
DECLARE_FLOAT(tx28);
DECLARE_FLOAT(tx29);
DECLARE_FLOAT(tx30);
DECLARE_FLOAT(tx31);
DECLARE_FLOAT(tx32);
DECLARE_FLOAT(tx33);
DECLARE_FLOAT(tx34);
DECLARE_FLOAT(tx35);


#endif
