#if USE_EXPLICIT_DECLARES
// declare variables
DECLARE_FLOAT(Energy);
DECLARE_FLOAT(StretchDeviation);
DECLARE_FLOAT(tx14);
DECLARE_FLOAT(tx15);
DECLARE_FLOAT(tx16);
DECLARE_FLOAT(tx17);
DECLARE_FLOAT(tx18);
DECLARE_FLOAT(tx19);
DECLARE_FLOAT(tx20);
DECLARE_FLOAT(tx21);
DECLARE_FLOAT(tx22);
DECLARE_FLOAT(tx23);
DECLARE_FLOAT(tx24);
DECLARE_FLOAT(tx25);
DECLARE_FLOAT(tx26);


#endif
